# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/a97b1c22-10d2-4d78-b17c-2442c6ddfb75";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-686f2f3c-98ec-42b3-a57b-d4d112f5392f".device = "/dev/disk/by-uuid/686f2f3c-98ec-42b3-a57b-d4d112f5392f";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4007-6C88";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/06c8e0dc-34e2-4bb3-96e4-0c7cba7076a1"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-426812b72157.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-6be5fa26404c.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-9c0dc444bc56.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-bb1510ac05ed.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-c3ea985bf0af.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-da4be46aeeb5.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0f3u1u1i5.useDHCP = lib.mkDefault true;
  # networking.interfaces.vboxnet0.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth6394b28.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
